# Generated by Django 4.1.13 on 2024-01-22 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Titan_app', '0008_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofiletitan',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUserTitan',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='UserProfileTitan',
        ),
    ]
