# Generated by Django 4.1.9 on 2023-11-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Titan_app', '0002_customusertitan_registration_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusertitan',
            name='nome',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
