# Generated by Django 4.1.9 on 2023-11-21 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Titan_app', '0003_customusertitan_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusertitan',
            name='registration_code',
        ),
    ]
