# Generated by Django 4.1.9 on 2023-11-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Titan_app', '0006_alter_customusertitan_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusertitan',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='userprofiletitan',
            name='bio',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
